---
title: "R Notebook"
output: html_notebook

---
```{r}
library(tidyverse)
library(ggplot2)
library(lmerTest)
library(lme4)
library(glue)
```
# Load Blimp configs
```{r}
blimp_configs = c('adjunct_island', 'anaphor_gender_agreement', 'anaphor_number_agreement', 'animate_subject_passive', 'animate_subject_trans', 'causative', 'complex_NP_island', 'coordinate_structure_constraint_complex_left_branch', 'coordinate_structure_constraint_object_extraction', 'determiner_noun_agreement_1', 'determiner_noun_agreement_2', 'determiner_noun_agreement_irregular_1', 'determiner_noun_agreement_irregular_2', 'determiner_noun_agreement_with_adj_2', 'determiner_noun_agreement_with_adj_irregular_1', 'determiner_noun_agreement_with_adj_irregular_2', 'determiner_noun_agreement_with_adjective_1', 'distractor_agreement_relational_noun', 'distractor_agreement_relative_clause', 'drop_argument', 'ellipsis_n_bar_1', 'ellipsis_n_bar_2', 'existential_there_object_raising', 'existential_there_quantifiers_1', 'existential_there_quantifiers_2', 'existential_there_subject_raising', 'expletive_it_object_raising', 'inchoative', 'intransitive', 'irregular_past_participle_adjectives', 'irregular_past_participle_verbs', 'irregular_plural_subject_verb_agreement_1', 'irregular_plural_subject_verb_agreement_2', 'left_branch_island_echo_question', 'left_branch_island_simple_question', 'matrix_question_npi_licensor_present', 'npi_present_1', 'npi_present_2', 'only_npi_licensor_present', 'only_npi_scope', 'passive_1', 'passive_2', 'principle_A_c_command', 'principle_A_case_1', 'principle_A_case_2', 'principle_A_domain_1', 'principle_A_domain_2', 'principle_A_domain_3', 'principle_A_reconstruction', 'regular_plural_subject_verb_agreement_1', 'regular_plural_subject_verb_agreement_2', 'sentential_negation_npi_licensor_present', 'sentential_negation_npi_scope', 'sentential_subject_island', 'superlative_quantifiers_1', 'superlative_quantifiers_2', 'tough_vs_raising_1', 'tough_vs_raising_2', 'transitive', 'wh_island', 'wh_questions_object_gap', 'wh_questions_subject_gap', 'wh_questions_subject_gap_long_distance', 'wh_vs_that_no_gap', 'wh_vs_that_no_gap_long_distance', 'wh_vs_that_with_gap', 'wh_vs_that_with_gap_long_distance')
```


```{r}
read_pretrained_pythia <- function(blimp_config, model_size, random_seed) {
  res = read_csv(glue("pretrained_results/blimp_{blimp_config}_pythia_{model_size}M_s{random_seed}.csv"))
  res$model_seed = random_seed
  res$model_size = model_size
  res$config = blimp_config
  return (res)
}
```

```{r}
read_pretrained <- function(blimp_config, model_name) {
  res = read_csv(glue("pretrained_results/blimp_{blimp_config}_{model_name}.csv"))
  res$model_name = model_name
  res$config = blimp_config
  return (res)
}
```

```{r, include=FALSE}
all_data_pythia_pretrained <- list()  # Initialize an empty list to store data frames
i <- 1  # Index for the list

pythia_model_sizes <- c(14, 70, 160, 410)

pythia_random_seeds <- c(1,2,3,4,5,6,7,8,9)

for (config in blimp_configs) {
  for (seed in pythia_random_seeds) {
    for (size in pythia_model_sizes) {
        res <- read_pretrained_pythia(config, size, seed)
        all_data_pythia_pretrained[[i]] <- res
        i <- i + 1
      }
    }
}
combined_data_pythia_pretrained <- do.call(rbind, all_data_pythia_pretrained)
```

```{r, include=FALSE}
all_data_pretrained = list()
i <- 1

model_names <- c(
  "mistralai_Mistral-7B-v0.3",
  "meta-llama_Llama-3.1-8B",
  "Qwen_Qwen3-8B",
  "EleutherAI_pythia-12b",
  "allenai_OLMo-2-1124-13B",
  "Qwen_Qwen3-14B",
  "google_gemma-3-27b-it"
)

for (model_name in model_names) {
  for (config in blimp_configs) {
    res <- read_pretrained(config, model_name)
    all_data_pretrained[[i]] <- res
    i <- i + 1
  }
}
combined_data_pretrained <- do.call(rbind, all_data_pretrained)
```
## Pythia Results

```{r}
accuracy.by.config.pythia<- combined_data_pythia_pretrained %>%
  mutate(model_seed=factor(model_seed),
         model_size = factor(model_size)) %>%
  group_by(config, model_seed, model_size) %>%
  summarize(accuracy=mean(correct)) %>%
  group_by(config, model_size)

accuracy.by.config.pythia.plt <- accuracy.by.config.pythia %>%
  ggplot(aes(x=accuracy, y=config)) + 
  geom_violin(fill="gray80") + 
  geom_boxplot(width=0.4, outlier.color = "steelblue") + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle=45, vjust=0.5)) + 
  labs(title="Pythia pretrained") + 
    facet_wrap(~model_size)

accuracy.by.config.pythia.plt
ggsave("exp9.accuracy.pdf", accuracy.by.config.pythia.plt, height=16, width=8)
```

```{r}
pythia.range.distribution <- accuracy.by.config.pythia %>%
  summarize(acc_range = max(accuracy) - min(accuracy)) 
```

```{r}
pythia.range.distribution.plt <- pythia.range.distribution %>%
  ggplot(aes(x = "", y = acc_range)) +
  geom_violin(trim = FALSE) +       # Violin plot; trim=FALSE shows full range
  geom_boxplot(width = 0.1,        # Optional: add a thin boxplot inside
               fill = "white", 
               outlier.shape = NA) +
  theme_minimal() +
  labs(title = "Distribution of Accuracy Range in Exp 9",
       y = "Max - Min") +
  theme(legend.position = "none")  +
  coord_cartesian(ylim=c(0,1)) + 
  facet_wrap(~model_size)
pythia.range.distribution.plt

ggsave("pythia.range.distribution.pdf", pythia.range.distribution.plt, height=12, width=8)

```

## Pretrained Results

```{r}
accuracy.pretrained <- combined_data_pretrained %>%
  group_by(model_name) %>%
  summarize(accuracy=mean(correct)) %>%
  ggplot(aes(x=model_name, y = accuracy, fill=model_name)) +
  geom_bar(stat = "identity") +
  scale_fill_brewer(palette = "YlOrRd") +   # warm palette
  theme_minimal()+
  guides(color = guide_legend(ncol = 1)) +
  theme(legend.position="bottom") + 
  ylim(0,1)
accuracy.pretrained
# ggsave("exp10.accuracy.collapsed.pdf", accuracy.pretrained, height=3, width=9)
```

```{r}
accuracy.by.config.pretrained <- combined_data_pretrained %>%
  mutate(model_name = factor(model_name, levels=c(
    "mistralai_Mistral-7B-v0.3",
    "meta-llama_Llama-3.1-8B",
    "Qwen_Qwen3-8B",
    "EleutherAI_pythia-12b",
    "allenai_OLMo-2-1124-13B",
    "Qwen_Qwen3-14B",
    "google_gemma-3-27b-it"))) %>%
  group_by(config, model_name) %>%
  summarize(accuracy=mean(correct)) %>%
  group_by(config)

accuracy.by.config.pretrained.plt <- accuracy.by.config.pretrained %>%
  ggplot(aes(x=accuracy, y=config)) +
  geom_violin(fill="gray80") +
  geom_boxplot(width=0.4, outlier.color = "steelblue") +
  geom_point(aes(color = model_name),
             position = position_jitter(height = 0.1, width = 0.0),
             size = 2, alpha = 0.8) +
  scale_color_brewer(palette = "YlOrRd") +  # warm palette
  theme_minimal() +
  theme(axis.text.x = element_text(angle=45, vjust=0.5),
        legend.position = "bottom") +
  guides(color = guide_legend(ncol = 2)) +
  labs(title="Pretrained") + coord_cartesian(xlim=c(0,1))

accuracy.by.config.pretrained.plt
ggsave("exp10.accuracy.pdf", accuracy.by.config.pretrained.plt, height=10, width=10)

```

```{r}
pretrained.range.distribution <- accuracy.by.config.pretrained %>%
  summarize(acc_range = max(accuracy) - min(accuracy)) 
pretrained.range.distribution
```

### Hypothesis testing
Does accuracy correlate with model size?
```{r}
accuracy.by.config.pretrained <- accuracy.by.config.pretrained %>%
  mutate(model_size = case_when(model_name == "mistralai_Mistral-7B-v0.3"~ 7,
                                model_name == "meta-llama_Llama-3.1-8B" ~ 8,
                                model_name == "Qwen_Qwen3-8B" ~ 8,
                                model_name == "EleutherAI_pythia-12b" ~ 12,
                                model_name == "allenai_OLMo-2-1124-13B" ~ 13,
                                model_name == "Qwen_Qwen3-14B" ~ 14,
                                model_name == "google_gemma-3-27b-it" ~ 27),
         model_size = factor(model_size))
```

```{r}
model.accuracy.size <- lmer(accuracy ~ model_size + (1 |config), data=accuracy.by.config.pretrained)
summary(model.accuracy.size)
```
Is there a model that do better than others? (assuming random intercept for config)
```{r}
model.accuracy.name <- lmer(accuracy ~ model_name + (1|config), data=accuracy.by.config.pretrained)
summary(model.accuracy.name)
```

